spring.application.name=coffeehouse-scheduler

# Path: Saves in your User folder. Use ./coffeedb to save next to the JAR instead.
spring.datasource.url=jdbc:h2:file:~/coffeedb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE

# Driver and Dialect
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Persistence: 'update' keeps existing data; 'create-drop' would delete it on exit.
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


# Log Hibernate's table creation
logging.level.org.hibernate.SQL=DEBUG

# Log the actual data.sql script execution
logging.level.org.springframework.jdbc.datasource.init.ScriptUtils=DEBUG

# (Optional) Show values being bound to parameters
logging.level.org.hibernate.type.descriptor.sql=TRACE

# Optional: Enable the H2 Console to view data in your browser at /h2-console
spring.h2.console.enabled=true
